# This file was generated by GoReleaser. DO NOT EDIT.
cask "tqrx" do
  name "tqrx"
  desc "Tiny Go QR generator with CLI and terminal UI"
  homepage "https://github.com/crper/tqrx"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tqrx"

  on_macos do
    on_intel do
      url "https://github.com/crper/tqrx/releases/download/v#{version}/tqrx_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/crper/tqrx/"
      sha256 "b7bca7b2fc051a038dbf59653bf5c3c8a674dc771bd7358c18a7d3b049836be0"
    end
    on_arm do
      url "https://github.com/crper/tqrx/releases/download/v#{version}/tqrx_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/crper/tqrx/"
      sha256 "b361e67a722cfb004d97778cff3fe571d47fc76b8f9fa99fb89779852ea3277b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crper/tqrx/releases/download/v#{version}/tqrx_#{version}_linux_amd64.tar.gz",
        verified: "github.com/crper/tqrx/"
      sha256 "ec9e85a55aad7857fc313c7a39d2f2191117a7986d6b60b9ca21360681d15103"
    end
    on_arm do
      url "https://github.com/crper/tqrx/releases/download/v#{version}/tqrx_#{version}_linux_arm64.tar.gz",
        verified: "github.com/crper/tqrx/"
      sha256 "59c362b365c581eb6891c7d8005cb60ac4385ad3f5ee135f1f905c375d8db45c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tqrx"]
    end
  end

  # No zap stanza required
end
