# This file was generated by GoReleaser. DO NOT EDIT.
cask "tqrx" do
  name "tqrx"
  desc "Tiny Go QR generator with CLI and terminal UI"
  homepage "https://github.com/crper/tqrx"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tqrx"

  on_macos do
    on_intel do
      url "https://github.com/crper/tqrx/releases/download/v#{version}/tqrx_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/crper/tqrx/"
      sha256 "5e5d23af109a06c9907288b4862827c68ddf87841d57d9dcd979baddbac6920f"
    end
    on_arm do
      url "https://github.com/crper/tqrx/releases/download/v#{version}/tqrx_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/crper/tqrx/"
      sha256 "08f8ddd40104d6ddb1d387fd78c3c219e1944250192a8645b268cee40335c1dc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crper/tqrx/releases/download/v#{version}/tqrx_#{version}_linux_amd64.tar.gz",
        verified: "github.com/crper/tqrx/"
      sha256 "75173eca55627b358e5bdfc8ae4deff9c8321d0fa85af1f0ae77633fb7bd20de"
    end
    on_arm do
      url "https://github.com/crper/tqrx/releases/download/v#{version}/tqrx_#{version}_linux_arm64.tar.gz",
        verified: "github.com/crper/tqrx/"
      sha256 "4f5ab5d1921495eac65d4ca1a60337a397ebf68830f16f9273b35d98a8939ef9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tqrx"]
    end
  end

  # No zap stanza required
end
