# This file was generated by GoReleaser. DO NOT EDIT.
cask "tqrx" do
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/crper/tqrx/releases/download/v#{version}/tqrx_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/crper/tqrx/"
      sha256 "21b3add06e7f9a99eda90c0522a14ab3a981e1e9da2763e97f070817fa3eeac1"
    end
    on_arm do
      url "https://github.com/crper/tqrx/releases/download/v#{version}/tqrx_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/crper/tqrx/"
      sha256 "76fbeed3b46026f32b8e2bcc2eeba7f681c79c4d164b97ecc3731b7e4c8e7e26"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crper/tqrx/releases/download/v#{version}/tqrx_#{version}_linux_amd64.tar.gz",
        verified: "github.com/crper/tqrx/"
      sha256 "b51eb48e1e3bb8a45f11b8a2fed4944412653f4af57a58a2461dca684cc5ab30"
    end
    on_arm do
      url "https://github.com/crper/tqrx/releases/download/v#{version}/tqrx_#{version}_linux_arm64.tar.gz",
        verified: "github.com/crper/tqrx/"
      sha256 "90ac2452f7417cf411e1413f287dea0b93ed6f2db19fea38043963a5f1caf17a"
    end
  end

  name "tqrx"
  desc "Tiny Go QR generator with CLI and terminal UI"
  homepage "https://github.com/crper/tqrx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tqrx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tqrx"]
    end
  end

  # No zap stanza required

end
